Enable implicit exception chaining when calling :meth:`generator.throw`.
